default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 'localhost'
  username: postgres
  password: postgres

development:
  <<: *default
  database: quero-respostas-api_development

test:
  <<: *default
  database: quero-respostas-api_test

production:
  <<: *default
  database: quero-respostas-api_production

